% MATLAB Editor Run Commands
% @version 4
% It is recommended that you do not edit this file directly, but use the
% Run button. Changes made to comments that exist outside of a
% configuration will not be saved.

%% @name getmapping
%  @associatedFile /MATLAB Drive/Reconnaissance de visages/getmapping.m
%  @mostRecentlyActioned true
%  @uniqueId CA8E8324

getmapping

%% @name test
%  @associatedFile /MATLAB Drive/Reconnaissance de visages/test.m
%  @mostRecentlyActioned true
%  @uniqueId C695CB35

test

